jtype: FaissLMDBSearcher
with:
  {}
metas:
  py_modules:  # THIS WILL NOT WORK SINCE IT RELIES ON CODE FILES FROM OTHER FOLDERS
    - __init__.py
    - faissfile.py
  workspace: workspace/
  name: faiss_file_searcher

